name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main-branch # Triggers when pushing to main-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build and Export Next.js
        run: npm run export

      - name: Push to Build Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan build-branch
          git rm -rf .
          mv out/* .
          rm -rf out .github node_modules
          git add .
          git commit -m "Deploy static build from main-branch"
          git push --force origin build-branch
