name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main # Runs when pushing to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build and Export Next.js
        run: npm run export # Uses the export script from package.json

      - name: Push to Build Branch (Keep Previous Builds)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Fetch the latest build-branch (if exists)
          git fetch origin build-branch || true
          git checkout build-branch || git checkout -b build-branch

          # Remove old build files while keeping Git history
          git rm -rf . 

          # Move new build files from "out" folder
          mv out/* .
          rm -rf out .github node_modules package-lock.json

          # Commit and push changes while keeping history
          git add .
          git commit -m "Deploy static build from main [$(date)]"
          git push origin build-branch
